sudo: required
dist: trusty
language: generic
compiler:
    - gcc
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libgmp-dev libmpc-dev libmpfr-dev lzip
script:
    - make -C tools
    - make -C tools setuid
    - cd distfiles && ./fetch.sh stage0 && cd ..
    - ./.test_stage0.sh
