sudo: required
dist: trusty
language: generic
compiler:
- gcc
addons:
  ssh_known_hosts:
  - famkaufmann.info
env:
- TEST_OPTION=stage0
- TEST_OPTION=stage1
before_install:
- openssl aes-256-cbc -K $encrypted_4cc4252d6764_key -iv $encrypted_4cc4252d6764_iv
  -in .travis_id_rsa.enc -out .travis_id_rsa -d
- sudo apt-get update -qq
- sudo apt-get install -qq libgmp-dev libmpc-dev libmpfr-dev lzip
script:
- ./.travis_test.sh
